name: gwas
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - pandas
  - fastparquet
  - seaborn
  - umap-learn
  - ipywidgets
  - dask
  - psycopg2
  - scikit-learn
  - openjdk=11
  - ipykernel
  - pyarrow
  - plink
  - snpeff
  - dask-jobqueue
  - gcta
  - plotly
  - biopython
  - pdf2image
  - poppler
  - mygene
  - pytables
  - h5py
  - pandas-plink
  - hdbscan
  - ydata-profiling
  - arviz
  - matplotlib-venn
  - prophet
  - lightgbm
  - shap
  - scikit-optimize
  - xgboost
  - nltk
  - pygraphviz
  - sqlalchemy
  - panel
  - hvplot
  - holoviews
  - fancyimpute
  - scikit-image
  - filterpy
  - datashader
  - pip
  - pip:
    - goatools
    - dash-bio==1.0.1
    - kaleido


